#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define SIXPACK_MAJOR_VERSION 0
#define SIXPACK_MINOR_VERSION 3
#define SIXPACK_PATCH_VERSION 0

#define SIXPACK_VERSION_LABEL ""

#define SIXPACK_FIRMWARE_VERSION STR(SIXPACK_MAJOR_VERSION) "." STR(SIXPACK_MINOR_VERSION) "." STR(SIXPACK_PATCH_VERSION) "-" SIXPACK_VERSION_LABEL